### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by Eunoia1729** [dhananjay1210/Leetcode-Downloader#1]
The code works fine till extracting all the submission links. But then it throws out this error:

Downloading your codes...
Traceback (most recent call last):
  File "leetcode_doenloader.py", line 569, in <module>
    que_name = driver.find_elements_by_xpath("/html/body/div[1]/div[3]/div[1]/div/div[1]/h4/a")[0].text
IndexError: list index out of range

**Comment by Eunoia1729** [comment]
I have found the bug and changed the code. Would you prefer a pull request ?

**Comment by dhananjay1210** [comment]
> The code works fine till extracting all the submission links. But then it throws out this error:
> 
> Downloading your codes...
> Traceback (most recent call last):
> File "leetcode_doenloader.py", line 569, in
> que_name = driver.find_elements_by_xpath("/html/body/div[1]/div[3]/div[1]/div/div[1]/h4/a")[0].text
> IndexError: list index out of range



> I have found the bug and changed the code. Would you prefer a pull request ?

Will you please elaborate on the bug and the solution? Thanks!

**Comment by dhananjay1210** [comment]
I just checked the code. It is fine. Just check the line 572 in code : 
Increase this timer to 15 if you have slow internet connection
time.sleep(10) 
The above error is due to submission for a particular problem could not be loaded within 6 seconds and this could be due to - 
1) Slow internet connection (In this case you can increase above delay, say, to 10)
2) Leetcode server is temporarily slow/down
3) Your PC is running too many applications causing your browser to slow down. 

Try running the same code after some time. Let me know if you are still facing any issues. Thanks:)

**Comment by dhananjay1210** [comment]
Closing this issue. 
Please feel free to raise issues!
